api:
  dashboard: true
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

certificatesResolvers:
  your_cert_resolver:
    acme:
      email: your_email@example.com
      storage: acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    endpoint: "npipe:////./pipe/docker_engine"
    exposedByDefault: false